---
# ArchLinux-specific task file for strongswan

- include_vars: arch.yml

- name: Install strongSwan
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ strongswan_packages }}"
