# Edit Host Files
#- name: Add IP address of all hosts to all hosts
#  lineinfile:
#    path: /etc/hosts
#    regexp: "((?=)^{{ hostvars[item].ansible_host }}|)"
#    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
#    state: present
#  with_items: "{{ groups.all }}"

  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK "
    insertafter: EOF
    block: |
      {% for item in groups.all %}
      "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
      {{% endfor %}