# Edit Host Files

#- name: Removing IP address of all hosts to all hosts
#  lineinfile:
#    path: /etc/hosts
#    regexp: "^{{ hostvars[item].ansible_host }}"
#    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
#    state: absent
#  with_items: "{{ groups.all }}"

#- debug:
#    msg: "{{ groups.all }}"
#
#- name: Add IP address of all hosts to all hosts
#  lineinfile:
#    path: /home/jamesni/hosts.txt
#    regexp: "^{{ hostvars[item].ansible_host }}"
#    insertafter: EOF
#    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
#    state: present
#    create: yes
#  with_items: "{{ groups.all }}"

- blockinfile:
    dest: /home/jamesni/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK "
    insertafter: EOF
    create: yes
    block: |
      {% for item in groups.all %}
      "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
      {% endfor %}

- blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK "
    insertafter: EOF
    block: |
      {% for item in groups.all %}
      "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
      {% endfor %}

- command: "cat /home/jamesni/hosts"
  register: homehosts

- debug:
    msg: "{{homehosts}}"

- command: "cat /etc/hosts"
  register: etchosts

- debug:
    msg: "{{etchosts}}"

