# Edit Host Files
- name: Add IP address of all hosts to all hosts
  lineinfile:
    path: /etc/hosts
    regexp: "((?=)^{{ hostvars[item].ansible_host }}|)"
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
    state: present
  with_items: "{{ groups.all }}"