# Edit Host Files
- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_host }}"
    insersafter: "^{{ hostvars[item].ansible_host }}"
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
    state: present
  with_items: "{{ groups.all }}"
