- name: Editing SELinux boolean values
  seboolean:
    name: "{{ item.name }}"
    persistent: "{{ item.persistent }}"
    state: "{{ item.state }}"
  with_items: "{{ selinux_boolean }}"

- name: disable selinux
  selinux:
    state: permissive
    policy: targeted
