- name: Install pre-requisite packages for wordpress
  yum: pkg={{item}} state=installed
  with_items:
    - MySQL-python
  notify: "restart nginx and php-fpm"

- name: disable selinux
  selinux:
    state: disabled

- name: Create wordpress root and logs directories
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ wordpress_root }}"
    - "{{ wordpress_logs }}"
  notify: "restart nginx and php-fpm"

- name:  update /etc/hosts with server name
  lineinfile:
    path: "{{ hosts_file }}"
    line: "^{{ ansible_host }} {{ inventory_hostname }}"
  notify: "restart nginx and php-fpm"

- name: download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
  become: true

- name: extract wordpress archive
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ wordpress_root }}"
    copy: no
    extra_opts: [--strip-components=1]
  become: true

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home="{{ wordpress_root }}"

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

- name: ensure wordpress.conf file exists
  copy:
    content: ""
    dest: "{{ wordpress_conf_dest }}"
    force: no
    owner: wordpress
    group: wordpress
    owner: wordpress
    mode: 0644

- name: Change ownership of WordPress installation
  file: path="{{ wordpress_root }}" owner=wordpress group=wordpress state=directory recurse=yes

- include: services.yml