- name: Install pre-requisite packages for wordpress
  yum: pkg={{item}} state=installed
  with_items:
    - MySQL-python
  notify: "restart nginx and php-fpm"

- name: disable selinux
  selinux:
    state: disabled

- name: Create wordpress root and logs directories
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ wordpress_root }}"
    - "{{ wordpress_logs }}"
  notify: "restart nginx and php-fpm"

- name:  update /etc/hosts with server name
  lineinfile:
    path: "{{ hosts_file }}"
    line: "^{{ ansible_host }} {{ inventory_hostname }}"
  notify: "restart nginx and php-fpm"

- name: download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: ~/wordpress.tar.gz
    validate_certs: no

- name: extract wordpress archive
  unarchive:
    src: ~/wordpress.tar.gz
    dest: "{{ wordpress_root }}"
    copy: no
    extra_opts: [--strip-components=1]

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home="{{ wordpress_root }}"

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

- name: ensure wordpress.conf file exists
  copy:
    content: ""
    dest: "{{ wordpress_conf_dest }}"
    force: no
    owner: wordpress
    group: wordpress
    mode: 0644

- name: Change ownership of WordPress installation
  file: 
    path: "{{ wordpress_root }}"
    state: directory
    owner: wordpress
    group: wordpress
    mode: 0755
    recurse: yes



- name: wpconfig
  copy:
    src: /usr/share/nginx/woabelfast/preview.woabelfast.co.uk/wp-config-sample.php
    dest: /usr/share/nginx/woabelfast/preview.woabelfast.co.uk/wp-config.php
    owner: wordpress
    group: wordpress
    mode: 0644
    remote_src: yes

- name: Update WordPress config file
  lineinfile:
    dest=/usr/share/nginx/woabelfast/preview.woabelfast.co.uk/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_db_name}}');"}        
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_db_user}}');"}        
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_db_password}}');"}
    - {'regexp': "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_HOST', '{{wp_db_host}}');"}
    - {'regexp': "define\\('WP_HOME', '(.)+'\\);", 'line': "define('WP_HOME', '{{wp_home}}');"}
    - {'regexp': "define\\('WP_SITEURL', '(.)+'\\);", 'line': "define('WP_SITEURL', '{{wp_site_url}}');"}
    - {'regexp': "define\\('WP_UPLOADS', '(.)+'\\);", 'line': "define('WP_UPLOADS', '{{wp_uploads}}');"}    

- include: services.yml