---

#Group vars for  bastion_servers


nginx_vhosts:
  - listen: "80"
    server_name: "jumpbox.com"
    root: "/var/www/jumpbox.com"
    index: "index.html index.htm"
    access_log: "/var/log/nginx/access.log"
    error_log: "/var/log/nginx/error.log"
    extra_parameters: |
      location / {

            proxy_set_header        Host $host:$server_port;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_read_timeout      300;
            proxy_connect_timeout   300;
            proxy_pass              http://10.120.0.6:8080;
            proxy_http_version 1.1;
            proxy_request_buffering off;
            proxy_buffering off;
            add_header 'X-SSH-Endpoint' '10.120.0.6:50022' always;
      }

firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "8080"

selinux_boolean: 
  - name: httpd_can_network_connect
    persistent: yes
    state: yes

custom_yum_installs:
  - libselinux-python
  - libsemanage-python
