 # Where will device be mounted EG /mnt/azure-storage-share
mount_path: /usr/share/nginx/{{ wordpress_server_name }}/wp-content/
 # Name of mounted device
mount_source: //sharedstorageaccount.file.core.windows.net/azure-storage-share/preview-wp
 # mounted device file system
filesystem: cifs
 # present/mounted/absent/unmounted
state: mounted
 # configure mount options
mount_options: vers=3.0,username=sharedstorageaccount,password=E68LH/ISQCltKJXv1wqP/mPwVPuJoFJT97T6uIQn9kvAWLL2s/xVhIYE+lbx2anRk6eC6+EDAsq78K6++CbzlQ==,defaults,uid=1000,gid=1000
nginx_vhosts:
  - listen: "80 default_server"
    server_name: "{{ wordpress_server_name }}" # default: N/A
    root: "{{ wordpress_root }}" # default: N/A
    index: "{{ wordpress_index }}" # default: "index.html index.htm"
    filename: "{{ wordpress_conf_name }}" # Can be used to set the filename of the vhost file.
    access_log: "{{ wordpress_access_log }}"
    error_log: "{{ wordpress_error_log }}"
    state: "present" # To remove the vhost configuration.
    extra_parameters: |
      location / {
        index index.php index.html index.htm;

        if (-f $request_filename) {
                expires 30d;
                break;
        }

        if (!-e $request_filename) {
          rewrite ^(.+)$ /index.php?q=$1 last;
        }
      }

      location ~ .php$ {
              fastcgi_pass   127.0.0.1:9000;  # port where FastCGI processes were spawned
              fastcgi_index  index.php;
              fastcgi_param  SCRIPT_FILENAME   {{ wordpress_root }}$fastcgi_script_name;  # same path as above
              fastcgi_param PATH_INFO               $fastcgi_script_name;
              include /etc/nginx/fastcgi_params;
              }

      location /elb_status {
              access_log off;
              return 200;
      }

  - listen: "80"
    server_name: "{{ php_server_name }}" # default: N/A
    root: "{{ php_root }}" # default: N/A
    index: "{{ php_index_files }}" # default: "index.html index.htm"
    filename: "{{ php_conf }}" # Can be used to set the filename of the vhost file.
    access_log: "{{ php_access_log }}"
    error_log: "{{ php_error_log }}"
    state: "present" # To remove the vhost configuration.
    extra_parameters: |
      location / {
        index index.html index.htm index.php;
      }

      location ~ \.php$ {
              include /etc/nginx/fastcgi_params;
              fastcgi_pass 127.0.0.1:9000;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME {{ php_root }}$fastcgi_script_name;
      }

  - listen: "80"
    server_name: "{{ phpmyadmin_server_name }}" # default: N/A
    root: "{{ phpmyadmin_root }}" # default: N/A
    index: "{{ phpmyadmin_index }}" # default: "index.html index.htm"
    filename: "{{ phpmyadmin_conf }}" # Can be used to set the filename of the vhost file.
    access_log: "{{ phpmyadmin_access_log }}"
    error_log: "{{ phpmyadmin_error_log }}"
    state: "present" # To remove the vhost configuration.
    extra_parameters: |
      location / {
        index  index.php;
      }

      location ~* ^.+.(jpg|jpeg|gif|css|png|js|ico|xml)$ {
        access_log        off;
        expires           30d;
      }

      location ~ /\.ht {
              deny  all;
      }

      location ~ /(libraries|setup/frames|setup/libs) {
              deny all;
              return 404;
      }

      location ~ \.php$ {
              include /etc/nginx/fastcgi_params;
              fastcgi_pass 127.0.0.1:9000;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME {{ phpmyadmin_root }}$fastcgi_script_name;
      }
