---
nginx_vhosts: 
- listen: "80" 
  server_name: "marc.testdomain"
  root: "usr/share/nginx/html/" 
  index: "index.html index.htm" 
  filename: "example.com.80.conf" 
  error_log: "/var/log/nginx/error.log"
  access_log: "/var/log/nginx/access.log"
  extra_parameters: |
    location / {
      proxy_pass http://10.120.0.3/;
    }




#  extra_parameters: |
#  location / {
#      proxy_pass http://10.120.0.3/;
#   }