 # Where will device be mounted EG /mnt/efs
mount_path: /mnt/efs/
 # Name of mounted device
mount_source: 
 # mounted device file system
filesystem: nfs4
 # Mount Options for device
mount_options: nfsvers4=4.1
 # present/mounted/absent/unmounted
state: mounted

nginx_vhosts:

  - listen: "80"
    server_name: "{{ wordpress_server_name }}" # default: N/A
    root: "{{ wordpress_root }}" # default: N/A
    index: "{{ wordpress_index }}" # default: "index.html index.htm"
    filename: "{{ wordpress_conf_name }}" # Can be used to set the filename of the vhost file.
    access_log: "{{ wordpress_access_log }}"
    error_log: "{{ wordpress_error_log }}"
    state: "present" # To remove the vhost configuration.
    extra_parameters: |
      location / {

      if (-f $request_filename) {
              expires 30d;
              break;
      }

      if (!-e $request_filename) {
              rewrite ^(.+)$ /index.php?q=$1 last;
              }
      }

      location ~ .php$ {
              fastcgi_pass   localhost:9000;  # port where FastCGI processes were spawned
              fastcgi_index  index.php;
              fastcgi_param  SCRIPT_FILENAME   {{ wordpress_root }}$fastcgi_script_name;  # same path as above
              fastcgi_param PATH_INFO               $fastcgi_script_name;
              include /etc/nginx/fastcgi_params;
              }

  - listen: "80"
    server_name: "{{ php_server_name }}" # default: N/A
    root: "{{ php_root }}" # default: N/A
    index: "{{ php_index_files }}" # default: "index.html index.htm"
    filename: "{{ php_conf }}" # Can be used to set the filename of the vhost file.
    access_log: "{{ php_access_log }}"
    error_log: "{{ php_error_log }}"
    state: "present" # To remove the vhost configuration.
    extra_parameters: |
      location / {

      if (-f $request_filename) {
              expires 30d;
              break;
      }

      if (!-e $request_filename) {
              rewrite ^(.+)$ /index.php?q=$1 last;
              }
      }

      location ~ .php$ {
              fastcgi_pass   localhost:9000;  # port where FastCGI processes were spawned
              fastcgi_index  index.php;
              fastcgi_param  SCRIPT_FILENAME   {{ php_root }}$fastcgi_script_name;  # same path as above
              fastcgi_param PATH_INFO               $fastcgi_script_name;
              include /etc/nginx/fastcgi_params;
              }

  - listen: "80"
    server_name: "{{ phpmyadmin_server_name }}" # default: N/A
    root: "{{ phpmyadmin_root }}" # default: N/A
    index: "{{ phpmyadmin_index }}" # default: "index.html index.htm"
    filename: "{{ phpmyadmin_conf }}" # Can be used to set the filename of the vhost file.
    access_log: "{{ phpmyadmin_access_log }}"
    error_log: "{{ phpmyadmin_error_log }}"
    state: "present" # To remove the vhost configuration.
    extra_parameters: |
      location / {

      if (-f $request_filename) {
              expires 30d;
              break;
      }

      if (!-e $request_filename) {
              rewrite ^(.+)$ /index.php?q=$1 last;
              }
      }

      location ~ .php$ {
              fastcgi_pass   localhost:9000;  # port where FastCGI processes were spawned
              fastcgi_index  index.php;
              fastcgi_param  SCRIPT_FILENAME   {{ phpmyadmin_root }}$fastcgi_script_name;  # same path as above
              fastcgi_param PATH_INFO               $fastcgi_script_name;
              include /etc/nginx/fastcgi_params;
              }