firewall_allowed_tcp_ports:
  - "22"
  - "4500"
  - "500"

custom_yum_installs:
  - strongswan

strongswan_conn:
  - name: strongswan
    conn:
      auto: route
      type: tunnel
      authby: psk
      keyexchange: ikev2
      lifetime: 3h
      ike: aes256gcm16-modp2048!
      esp: aes256gcm16-modp2048!
      ikelifetime: 24h
    left:
      address: "{{ hostvars['dmz_strongswan'].ansible_host }}"
      subnet: 10.120.0.0/24
      protoport: 47
      id: my
      updown: /usr/lib/ipsec/_updown_nat
    right:
      address: 51.141.117.196
      subnet: 172.16.254.0/24
      protoport: 47
      id: your
      updown: /usr/lib/ipsec/_updown_nat
    secret: something_needs_to_go_here

