---

postgresql_users:
  - name: zabbix-server
    password: zabbix-server

zabbix_url: zabbix.woabelfast.co.uk
zabbix_timezone: Europe/London
zabbix_server_database: pgsql
zabbix_server_database_long: postgresql

# postgresql_db:
#   - name: zabbix
#     port: '5432'
#     state: present 






