firewall_allowed_tcp_ports:
  - "22"
  - "4500"
  - "500"

custom_yum_installs:
  - strongswan

strongswan_conn:
  - name: strongswan
    conn: azure
    auto: start
    type: tunnel
    authby: secret
    keyexchange: ikev2
    lifetime: 3h
    ike: 3des-sha1-modp1024,aes128-sha1-modp1024
    esp: 3des-sha1,aes128-sha1
    ikelifetime: 10800s
    keylife: 57m
    keyingtries: 1
    compress: no
    rekeymargin: 3m
    left:
      address: "{{ hostvars['dmz_strongswan'].ansible_host }}"
      id: "{{ hostvars['dmz_strongswan'].ansible_host }}"
      subnet: 10.120.0.0/16
      sendcert: never
    right:
      address: 51.141.117.196
      id: 51.141.117.196 
      subnet: 172.16.0.0/16
    secret: something_needs_to_go_here

