# nginx vhost

nginx_vhosts: 
 - listen: "80" # default: "80"
   server_name: "preview.woabelfast.co.uk" # default: N/A
   root: "/var/www/preview.woabelfast.co.uk" # default: N/A
   index: "index.html index.htm" # default: "index.html index.htm"
   filename: "preview.woabelfast.co.uk.conf" # Can be used to set the filename of the vhost file.
   extra_parameters: |
      location / {
        proxy_pass http://preview-wordpress-elb-587527805.eu-west-1.elb.amazonaws.com:80
      }
