#woabelfast folder
  - name: Check if woabelfast exists
    stat: path=/usr/share/nginx/woabelfast
    register: woa

  - file:
      path: /usr/share/nginx/woabelfast
      state: directory
      mode: 0755
    when: woa.stat.exists == false

# mnt the filesystem folder
  - name: Check if filesystem folder exists
    stat: path="{{ mount_path }}"
    register: mounted_filesystem

  - file:
      path: "{{ mount_path }}"
      state: directory
      mode: 0755
    when: mounted_filesystem.stat.exists == false

# edit /etc/fstab for cifs

  - lineinfile:
      path: "{{ fstab }}"
      line: "{{ fstab_config }}"
    when: mounted_filesystem == "cifs"

# Creating Symbolic Link
  - file:
      dest: /usr/share/nginx/woabelfast
      src: "{{ mount_path }}"
      state: link 
      force: yes

# Mount drive
  - name: Mounting Device
    mount:
      path: "{{ mount_path }}"
      src: "{{ mount_source }}"
      fstype: "{{ filesystem }}"
      state: "{{ state }}" 
    