#woabelfast folder
  - name: Check if woabelfast exists
    stat: path="/usr/share/nginx/{{ wordpress_server_name }}"
    register: woa

  - file:
      path: "/usr/share/nginx/{{ wordpress_server_name }}"
      state: directory
      mode: 0755
    when: woa.stat.exists == false

# mnt the filesystem folder
  - name: Check if filesystem folder exists
    stat: path="{{ mount_path }}"
    register: mount

  - file:
      path: "{{ mount_path }}"
      state: directory
      mode: 0755
    when: mount.stat.exists == false

## Creating Symbolic Link
#  - file:
#      dest: "/usr/share/nginx/{{ wordpress_server_name }}/wp-content/media"
#      src: "{{ mount_path }}"
#      state: link 
#      force: yes

# Mount drives
  - name: Mounting Device
    mount:
      path: "{{ mount_path }}"
      src: "{{ mount_source }}"
      fstype: "{{ filesystem }}"
      state: "{{ state }}" 
      opts: "{{ mount_options }}"
    