---
- name: install PHP components
  yum: pkg=php-{{item}} state=installed
  with_items:
    - fpm
    - mysql
    - cli
    - pear

- name: check if epel is installed
  stat: path=/etc/yum.repos.d/epel.repo
  register: epel_repofile_result

- name: install epel if not already installed
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists

- name: import epel gpg key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists

- name: install php, phpmyadmin and zendopcache components from epel
  yum: pkg={{item}} state=installed
  enablerepo: epel
  with_items:
    - php
    - phpmyadmin
    - php-pecl-zendopcache

- name: Remove epel repo
  yum_repository:
    name: epel-release
    state: absent
  notify: yum-clean-metadata

- name: change cgi.fix_pathinfo= to value of 0 in /etc/php.ini
  lineinfile:
    path: "{{ php_ini_path }}"
    regexp: "^{{ php_ini_cgi_string }}"
    line: "{{ php_ini_cgi }}"

- name: create woabelfast.co.uk directory
  file: path={{ php_filesystem }}{{ item }} state=directory
  with_items:
    - "{{ php_server_name }}"
    - "{{ server_hostname }}"

- name: ensure index.php file exists
  copy:
    content: ""
    dest: "{{ phpfpm_dest }}"
    force: no
    group: nginx
    owner: nginx
    mode: 0644

- name: create php info page
  lineinfile:
    path: "{{ phpfpm_dest }}"
    line: <?php phpinfo(); ?>
  notify: "restart nginx and php-fpm"

- name: update values in /etc/php.d/opcache.ini
  lineinfile:
    path: "{{ opache_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^{{ opcache_revalidate_freq_string }}", line: "{{ opcache_revalidate_freq }}" }
    - { regexp: "^{{ opcache_validate_timestamps_string }}", line: "{{ opcache_validate_timestamps }}" }
    - { regexp: "^{{ opcache_accelerated_files_string }}", line: "{{ opcache_accelerated_files }}" }
    - { regexp: "^{{ opcache_memory_consumption_string }}", line: "{{ opcache_memory_consumption }}" }
    - { regexp: "^{{ opcache_interned_strings_buffer_string }}", line: "{{ opcache_interned_strings_buffer }}" }
    - { regexp: "^{{ opcache_fast_shutdown_string }}", line: "{{ opcache_fast_shutdown }}" }
