- name: restart_mariadb
  service: name=mariadb state=restarted

- name: restart_nginx
  service: name=nginx state=restarted
  listen: "restart nginx and php-fpm"

- name: restart_php-fpm
  service: name=php-fpm state=restarted
  listen: "restart nginx and php-fpm"