---
- hosts: all
  become: true
  gather_facts: true
  roles:
    - { role: common, tags: 'base' }
    - willshersystems.sshd
    - geerlingguy.firewall
    - singleplatform-eng.users
    - yum_packages

- name: Install NGINX on proxy
  hosts:
    - tag_Role_webserver
    - Role_webserver
  become: true
  roles:
    - geerlingguy.nginx

- name: configure wordpress
  hosts: 
    - tag_Role_wordpress
    - Role_wordpress
  become: true
  roles:
    - yum_packages
    - geerlingguy.nginx
    - PHP
    - wordpress
    - mount_folder

- name: configure jenkins
  hosts: tag_Role_jenkins
  become: true
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - pip_packages

- name: Install and Configure mySQl on DB server
  hosts: tag_Role_db
  become: true
  roles:
    - geerlingguy.mysql

- name: configure bastion servers
  hosts: 
    - tag_Role_bastion
    - Role_bastion
  become: true
  roles:
    - geerlingguy.nginx

- name: configure strongswan
  hosts: 
    - tag_Role_strongswan
  become: true
  roles: 
    - strongswan

  - name: configure zabix agents
    role: dj-wasabi.zabbix-agent
       zabbix_agent_server: 192.168.33.30
       zabbix_agent_serveractive: 192.168.33.30
       zabbix_url: http://zabbix.example.com
       zabbix_api_use: true 
       zabbix_api_user: Admin
       zabbix_api_pass: zabbix
       zabbix_create_host: present
       zabbix_host_groups:
         - Linux Servers
       zabbix_link_templates:
         - Template OS Linux
         - Apache APP Template
       zabbix_macros:
         - macro_key: apache_type
           macro_value: reverse_proxy
    hosts:
      - tag_Role_preview_webserver
      - tag_Role_preview_wordpress
      - Role_preview_webserver
      - Role_preview_webserver