---
- hosts: all
  become: true
  gather_facts: true
  roles:
    - common
    - willshersystems.sshd
    - NTP
    - geerlingguy.firewall
    - singleplatform-eng.users

- name: Install NGINX on proxy
  hosts: webservers
  become: true
  roles:
    - geerlingguy.nginx

- name: configure wordpress
  hosts: wordpress_servers
  become: true
  roles:
    - geerlingguy.nginx
    - PHP
    - wordpress
    
- name: configure jenkins
  hosts: jenkins_servers
  become: true
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins

- name: Install and Configure mySQl on DB server
  hosts: db_servers
  become: true
  roles: 
    - geerlingguy.mysql
