---
- hosts: all
  become: true
  gather_facts: true
  roles:
    - common
    - willshersystems.sshd
    - NTP

- name: Install NGINX on proxy
  hosts: webservers
  become: true
  roles:
    - geerlingguy.nginx