---
- hosts: all
  become: true
  gather_facts: true
  roles:
    - common
    - willshersystems.sshd
    - NTP
    - geerlingguy.firewall
    - singleplatform-eng.users
    
- name: Install NGINX on proxy
  hosts: webservers
  become: true
  roles:
    - geerlingguy.nginx

- name: configure wordpress
  hosts: wordpress_servers
  become: true
  roles:
    - PHP
