# -*- mode: ruby -*-
# vi: set ft=ruby :
hosts = [
    # Preview
    {name: 'preview-proxy-01', ip: '10.122.1.2', memory: '512', cpu: '2', hostname: 'preview-proxy01.woabelfast.local', disk: "false"},
    {name: 'preview-proxy-02', ip: '10.122.1.3', memory: '512', cpu: '2', hostname: 'preview-proxy02.woabelfast.local', disk: "false"},
    {name: 'preview-wordpress-01', ip: '10.122.2.4', memory: '512', cpu: '2', hostname: 'preview-wordpress01.woabelfast.local', disk: "true"}, 
    {name: 'preview-wordpress-02', ip: '10.122.2.5', memory: '512', cpu: '2', hostname: 'preview-wordpress02.woabelfast.local', disk: "true"},

    # Pre-prod
    {name: 'preprod-proxy-01', ip: '10.132.1.2', memory: '512', cpu: '2', hostname: 'preprod-proxy01.woabelfast.local', disk: "false"},
    {name: 'preprod-proxy-02', ip: '10.132.1.3', memory: '512', cpu: '2', hostname: 'preprod-proxy02.woabelfast.local', disk: "false"},
    {name: 'preprod-wordpress-01', ip: '10.132.2.4', memory: '512', cpu: '2', hostname: 'preprod-wordpress01.woabelfast.local', disk: "true"}, 
    {name: 'preprod-wordpress-02', ip: '10.132.2.5', memory: '512', cpu: '2', hostname: 'preprod-wordpress02.woabelfast.local', disk: "true"},

    # Production
    {name: 'production-proxy-01', ip: '10.142.1.2', memory: '512', cpu: '2', hostname: 'production-proxy01.woabelfast.local', disk: "false"},
    {name: 'production-proxy-02', ip: '10.142.1.3', memory: '512', cpu: '2', hostname: 'production-proxy02.woabelfast.local', disk: "false"},
    {name: 'production-wordpress-01', ip: '10.142.2.4', memory: '512', cpu: '2', hostname: 'production-wordpress01.woabelfast.local', disk: "true"},
    {name: 'production-wordpress-02', ip: '10.142.2.5', memory: '512', cpu: '2', hostname: 'production-wordpress02.woabelfast.local', disk: "true"},

    {name: 'db', ip: '10.122.3.6', memory: '512', cpu: '2', hostname: 'db.woabelfast.local', disk: "false"},
    {name: 'dmz-jumpbox', ip: '10.120.0.7', memory: '512', cpu: '2', hostname: 'dmz-jumpbox.woabelfast.local', disk: "false"},
    {name: 'management-jenkins', ip: '10.121.0.8', memory: '512', cpu: '2', hostname: 'management-jenkins.woabelfast.local', disk: "false"}
]

groups = {  
    "bastion-servers" => ["dmz-jumpbox"],
    "jenkins-servers" => ["management-jenkins"],
    "db-servers" => ["db"],

    "preview-webservers" => ["preview-proxy-01", "preview-proxy-02"],
    "preview-wordpress" => ["preview-wordpress-01", "preview-wordpress-02"],
    "preview:children" => ["preview-wordpress", "preview-webservers"],

    "preprod-webservers" => ["preprod-proxy-01", "preprod-proxy-02"],
    "preprod-wordpress" => ["preprod-wordpress-01", "preprod-wordpress-02"],
    "preprod:children" => ["preprod-wordpress", "preprod-webservers"],

    "production-webservers" => ["preview-proxy_01", "preview-proxy-02"],
    "production-wordpress" => ["preview-wordpress_01", "preview-wordpress-02"],
    "production:children" => ["preview-wordpress", "preview-webservers"],

    "webservers:children" => ["preview-webservers", "preprod-webservers", "production-webservers"],
    "wordpress-servers:children" => ["preview-wordpress", "preprod-wordpress", "production-wordpress"]
}


Vagrant.configure("2") do |config|

  hosts.each do |host|
    config.vm.define host[:name] do |c|
      c.vm.box = "centos/7"
      c.vm.hostname = host[:hostname]
      c.vm.network  "private_network",ip: host[:ip] ,netmask: "255.255.255.0"
      c.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
        ansible.groups = groups
        ansible.galaxy_role_file = "requirements.yml"
        ansible.galaxy_roles_path = 'roles_galaxy'
        ansible.extra_vars = {
          wp_db_host: "10.122.3.6",
          wp_db_name: "wordpress",
          wp_db_user: "wpuser",
          wp_db_password: "123456789",
    } 

      end
      c.vm.provider "virtualbox" do |vb|
        vb.memory = host[:memory]
        vb.cpus = host[:cpu]
        if host[:disk] == "true"
          disk = "#{host[:name]}.vdi"
          unless File.exist?(disk)
            vb.customize ['createhd', '--filename', disk, '--size', 1 * 1024]
            vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
          end
        end
      end
    end
  end
end