# -*- mode: ruby -*-
# vi: set ft=ruby :
hosts = [
    # Preview
    {name: 'preview-proxy01', ip: '10.122.1.2', memory: '512', cpu: '2', hostname: 'preview-proxy01.woabelfast.local', disk: "false"},
    {name: 'preview-proxy02', ip: '10.122.1.3', memory: '512', cpu: '2', hostname: 'preview-proxy02.woabelfast.local', disk: "false"},
    {name: 'preview-wordpress01', ip: '10.122.2.4', memory: '512', cpu: '2', hostname: 'preview-wordpress01.woabelfast.local', disk: "true"},
    {name: 'preview-wordpress02', ip: '10.122.2.5', memory: '512', cpu: '2', hostname: 'preview-wordpress02.woabelfast.local', disk: "true"},

    # Pre-prod
    {name: 'preprod-proxy01', ip: '10.132.1.2', memory: '512', cpu: '2', hostname: 'preprod-proxy01.woabelfast.local', disk: "false"},
    {name: 'preprod-proxy02', ip: '10.132.1.3', memory: '512', cpu: '2', hostname: 'preprod-proxy02.woabelfast.local', disk: "false"},
    {name: 'preprod-wordpress01', ip: '10.132.2.4', memory: '512', cpu: '2', hostname: 'preprod-wordpress01.woabelfast.local', disk: "true"},
    {name: 'preprod-wordpress02', ip: '10.132.2.5', memory: '512', cpu: '2', hostname: 'preprod-wordpress02.woabelfast.local', disk: "true"},

    # Production
    {name: 'production-proxy01', ip: '10.142.1.2', memory: '512', cpu: '2', hostname: 'production-proxy01.woabelfast.local', disk: "false"},
    {name: 'production-proxy02', ip: '10.142.1.3', memory: '512', cpu: '2', hostname: 'production-proxy02.woabelfast.local', disk: "false"},
    {name: 'production-wordpress01', ip: '10.142.2.4', memory: '512', cpu: '2', hostname: 'production-wordpress01.woabelfast.local', disk: "true"},
    {name: 'production-wordpress02', ip: '10.142.2.5', memory: '512', cpu: '2', hostname: 'production-wordpress02.woabelfast.local', disk: "true"},

    {name: 'db', ip: '10.122.3.6', memory: '512', cpu: '2', hostname: 'db.woabelfast.local', disk: "false"},
    {name: 'dmz-jumpbox', ip: '10.120.0.7', memory: '512', cpu: '2', hostname: 'dmz-jumpbox.woabelfast.local', disk: "false"},
    {name: 'management-jenkins', ip: '10.121.0.8', memory: '512', cpu: '2', hostname: 'management-jenkins.woabelfast.local', disk: "false"}
]

groups = {
    "tag_Role_bastion" => ["dmz-jumpbox"],
    "tag_Role_jenkins" => ["management-jenkins"],
    "tag_Role_db" => ["db"],

    "tag_EnvRole_preview_webserver" => ["preview-proxy01", "preview-proxy02"],
    "tag_EnvRole_preview_wordpress" => ["preview-wordpress01", "preview-wordpress02"],
    "tag_Environment_preview:children" => ["tag_EnvRole_preview_webserver", "tag_EnvRole_preview_wordpress"],

    "tag_EnvRole_preprod_webserver" => ["preprod-proxy01", "preprod-proxy02"],
    "tag_EnvRole_preprod_wordpress" => ["preprod-wordpress01", "preprod-wordpress02"],
    "tag_Environment_preprod:children" => ["tag_EnvRole_preprod_webserver", "tag_EnvRole_preprod_wordpress"],

    "tag_EnvRole_production_webserver" => ["preview-proxy01", "preview-proxy02"],
    "tag_EnvRole_production_wordpress" => ["preview-wordpress01", "preview-wordpress02"],
    "tag_Environment_production:children" => ["preview-wordpress", "preview-webservers"],

    "tag_Role_webserver:children" => ["tag_EnvRole_preview_webserver", "tag_EnvRole_preprod_webserver", "tag_EnvRole_production_webserver"],
    "tag_Role_wordpress:children" => ["tag_EnvRole_preview_wordpress", "tag_EnvRole_preprod_wordpress", "tag_EnvRole_production_wordpress"]
}


Vagrant.configure("2") do |config|

  config.landrush.enabled = true
  config.landrush.tld = 'woabelfast.local'

  hosts.each do |host|
    config.vm.define host[:name] do |c|
      c.vm.box = "centos/7"
      c.vm.hostname = host[:hostname]
      c.vm.network  "private_network",ip: host[:ip] ,netmask: "255.255.255.0"
      c.vm.provision "shell", inline: <<-SHELL
        if grep -qs '/dev/sdb ' /proc/mounts; then
          sudo umount /dev/sdb/
        fi
        sudo mkfs.ext3 /dev/sdb -F
        SHELL
      c.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
        ansible.vault_password_file = ".vault_pass"
        ansible.groups = groups
        ansible.galaxy_role_file = "requirements.yml"
        ansible.galaxy_roles_path = 'roles_galaxy'
        ansible.extra_vars = {
          wp_db_host: "10.122.3.6",
          wp_db_name: "wordpress",
          wp_db_user: "wpuser",
          wp_db_password: "123456789",
          mount_source: "/dev/sdb",
          filesystem: "ext3",
        } 
      end
      c.vm.provider "virtualbox" do |vb|
        vb.memory = host[:memory]
        vb.cpus = host[:cpu]
        if host[:disk] == "true"
          disk = "#{host[:name]}.vdi"
          unless File.exist?(disk)
            vb.customize ['createhd', '--filename', disk, '--size', 1 * 1024]
            vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
          end
        end
      end
      if host[:disk] == "true"
        disk = "#{host[:name]}.vdi"
            if File.exist?(disk)
                c.trigger.after :destroy do |trigger|
                    trigger.warn = "Deleting provisioned disk on destroy:"
                    trigger.run = {inline: "rm -f #{disk}"}
                    trigger.info = "Disk deleted for #{host[:name]}"
                end
            else
                puts "#{host[:name]} has no disk to delete"
            end
        end
    end
  end
end
